# Generated by Django 2.2.16 on 2022-07-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220719_1906'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Пользователь уже подписан на данного автора',
        ),
    ]
